### ISSUE TITLE
compressor confusion

### ISSUE THREAD

**Issue by Linrox** [sirrobzeroone/elepower#10]
I noticed that the recipe for creating a compressor requires a bronze plate.
Unless i am missing something, to create a bronze plate you need a compressor.
So i need a compressor to make a bronze plate, and i need a bronze plate to create a compressor?
confused?

**Comment by Awkanimus** [comment]
I see two recipes for the piston...one which requires a bronze plate, and one which has three copper on the row where the bronze plate is. Do you.have that second recipe available?

**Comment by dax-er** [comment]
there are two recipes: the first one with ingots is meant for you first compressor so you can make plates to craft more compressors for a cheaper price than with ingots.

**Comment by Linrox** [comment]
I no longer play minecraft due to MS.
