### ISSUE TITLE
This mod may become depreciated soon.

### ISSUE THREAD

**Issue by DustyBagel** [sirrobzeroone/elepower#21]
Some of the nodes in this mod use the use_texture_alpha texture setting which will no longer be supported in 5.9.0. This needs to be changed or the mod may be depreciated in 5.9.0.

**Comment by dax-er** [comment]
> This mod may become depreciated soon.

It's deprecated, not depreciated.

> Some of the nodes in this mod use the use_texture_alpha texture setting which will no longer be supported in 5.9.0.

`use_texture_alpha` is still supported, it's quite the opposite actually. if you *don't* use this property, then the textures with transparent pixels will look wrongly opaque.

> This needs to be changed or the mod may be depreciated in 5.9.0.

This mod isn't being actively developed anyway, so if it has a problem it is unlikely to be fixed.

**Comment by DustyBagel** [comment]
It seems that the compatibility code for use_texture_alpha for nodeboxes and meshes is being removed in 5.9.0.
I thought it was just being deprecated altogether because other mods I use have been using it and on 5.9.0 dev builds their textures weren't looking right.
